
// Engineering Version Control System
// Format: Major.Minor.Patch
export const APP_VERSION = "4.2.0";

// Build ID: Usually generated by CI/CD.
// Here we simulate a commit hash/build timestamp.
export const BUILD_ID = "SMART-INTERACTION";

export const getFullVersion = () => `v${APP_VERSION}`;
